# Generated by Django 4.2 on 2023-04-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('header', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='stipendii_photo')),
            ],
        ),
    ]
