# Generated by Django 4.2 on 2023-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='image',
            field=models.ImageField(blank=True, upload_to='stipendii_image'),
        ),
    ]
