# Generated by Django 4.2 on 2023-04-24 08:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_alter_scholarship_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='detail_image',
            field=models.ImageField(blank=True, upload_to='detail_image'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
