# Generated by Django 4.2 on 2023-04-24 12:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_scholarship_detail_image_alter_scholarship_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
