# Generated by Django 4.2 on 2023-04-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactaddress',
            options={'verbose_name': 'ContactAddress', 'verbose_name_plural': 'ContactAddress'},
        ),
    ]
