# Generated by Django 4.2 on 2023-04-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ManyToManyField(to='event.eventtype'),
        ),
        migrations.DeleteModel(
            name='EventEventType',
        ),
    ]
